language: node_js
cache: yarn
node_js:
  - 8
  - 9
before_install:
  - sudo add-apt-repository ppa:git-core/ppa -y
  - sudo apt-get update
  - sudo apt-get install realpath
  - sudo apt-get install git
install:
  - yarn
script:
  - yarn test
