version: 2
jobs:
 build:
   machine: true

   working_directory: ~/repo

   steps:
     - checkout
     - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-
     - run: sudo add-apt-repository ppa:git-core/ppa -y
     - run: sudo apt-get update
     - run: sudo apt-get install realpath
     - run: sudo apt-get install git
     - run: sudo apt-get install yarn
     - run: yarn

     - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

     - run: yarn test
