version: 2
jobs:
 build:
   docker:
     - image: circleci/node:7.10

   steps:
     - checkout
     - run: sudo add-apt-repository ppa:git-core/ppa -y
     - run: sudo apt-get update
     - run: sudo apt-get install realpath
     - run: sudo apt-get install git
     - run: yarn

     - save_cache:
         paths:
             - node_modules

     - run: yarn test
