version: 2
jobs:
 build:
   docker:
     - image: node:9.11.1

   steps:
     - checkout
     - restore_cache:
         keys:
         - v1-dependencies-{{ checksum "package.json" }}
         # fallback to using the latest cache if no exact match is found
         - v1-dependencies-
     - run: add-apt-repository ppa:git-core/ppa -y
     - run: apt-get update
     - run: apt-get install realpath
     - run: apt-get install git
     - run: yarn

     - save_cache:
         paths:
           - node_modules
         key: v1-dependencies-{{ checksum "package.json" }}

     - run: yarn test
