# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
 build:
   working_directory: ~/repo

   steps:
     - checkout
     - run: sudo add-apt-repository ppa:git-core/ppa -y
     - run: sudo apt-get update
     - run: sudo apt-get install realpath
     - run: sudo apt-get install git
     - run: yarn

     - save_cache:
         paths:
           - node_modules

     - run: yarn test
