#!/usr/bin/env node
const Program = require('commander');
const LocalStorage = require('../local-storage');
const Package = require('../package');

/**
  Package CLI.
 */

Program
  .command('update-deps')
  .description('Updates dependencies and auto-solves conflicts')
  .action((options) => {
    LocalStorage.assertTortilla(true);
    Package.updateDependencies();
  });

Program.parse(process.argv);
