#!/usr/bin/env node
var Program = require('commander');
var LocalStorage = require('../src/local-storage');
var Step = require('../src/step');

/**
  Step CLI.
 */

Program
  .command('push')
  .description('Pushes a new step')
  .option('-m, --message [message]', 'A message describing the newly created step')
  .option('--allow-empty', 'Allow an empty step to be pushed')
  .action(function (options) {
    LocalStorage.assertTortilla(true);
    Step.push(options.message, options);
  });

Program
  .command('pop')
  .description('Pops the most recent step')
  .action(function () {
    LocalStorage.assertTortilla(true);
    Step.pop();
  });

Program
  .command('tag')
  .description('Mark this step as finished and move on to the next one')
  .option('-m, --message [message]', 'A message describing the newly created step')
  .action(function (options) {
    LocalStorage.assertTortilla(true);
    Step.tag(options.message);
  });

Program
  .command('edit [step]')
  .description('Edits the specified step')
  .option('--root [root]', 'Edit the root step (initial commit)')
  .action(function (step, options) {
    LocalStorage.assertTortilla(true);
    step = step || (options.root && 'root');
    Step.edit(step);
  });

Program
  .command('sort [step]')
  .description('Adjust all step indexes from a given step index')
  .option('--root [root]', 'Adjust from root commit')
  .action(function (step, options) {
    LocalStorage.assertTortilla(true);
    step = step || (options.root && 'root');
    Step.sort(step);
  });

Program
  .command('reword [step]')
  .description('Rename the specified step\'s commit message')
  .option('-m, --message [message]', 'The new message of the reworded step')
  .option('--root', 'Reword the root step (initial commit)')
  .action(function (step, options) {
    LocalStorage.assertTortilla(true);
    step = step || (options.root && 'root');
    Step.reword(step, options.message);
  });

Program.parse(process.argv);
