#!/usr/bin/env node
var Program = require('commander');
var Pack = require('../package.json');
var Essentials = require('../src/essentials');
var LocalStorage = require('../src/local-storage');

/**
  CLI entry point.
 */

Program
  .version(Pack.version)
  .description(Pack.description);

Program
  .command('create [name]')
  .description('Create a new tortilla project named [name]')
  .option('-o, --output [path]', 'The output [path] for the newly created project')
  .option('-m, --message [message]', 'The [message] of the root commit')
  .option('--override', 'Override dir if already exists')
  .action(function (name, options) {
    Essentials.create(name, options);
  });

Program
  .command('init [dir]')
  .description('Initialize Tortilla essentials in the provided project [dir]')
  .action(function (dir) {
    var localStorage = dir ? LocalStorage.create(dir) : LocalStorage;
    localStorage.assertTortilla();
    Essentials.ensure(dir);
  });

Program
  .command('manual <command...>', 'Manage manual files')
  .command('step <command...>', 'Manage step commits history')
  .command('strict <command...>', 'Manage strict mode')
  .command('release <command...>', 'Manage tutorial releases');

Program.parse(process.argv);
