#!/usr/bin/env node
var Program = require('commander');
var Version = require('version');
var LocalStorage = require('../src/local-storage');

/*
  Version CLI.
 */

Program
  .command('bump <type>')
  .description('Bump current version by the provided <type>')
  .option('-m, --message [message]', 'A [message] describing the new version')
  .action(function (type, options) {
    LocalStorage.assertTortilla(true);
    Version.bump(type, options);
  });

Program
  .command('current')
  .description('Prints the current version')
  .action(function () {
    LocalStorage.assertTortilla(true);
    var currentVersion = Version.current();
    var formattedVersion = Version.format(currentVersion);
    console.log(formatVersion);
  });

Program.parse(process.argv);
