#!/usr/local/bin/node
var Program = require('commander');
var LocalStorage = require('../src/local-storage');
var Manual = require('../src/manual');

/*
  Manual CLI.
 */

Program
  .command('convert [step]')
  .description('Convert [step] manual to its opposite format')
  .option('--root', 'Convert \'README.md\'')
  .option('--all', 'Convert all manuals through out history')
  .option('--prod', 'Convert manual to production format')
  .option('--dev', 'Convert manual to development format')
  .action(function (step, options) {
    LocalStorage.assertTortilla(true);

    step = step || (options.root && 'root');
    step = step || (options.all && 'all');

    if (!options.dev && !options.prod) {
      options.prod = true;
      options.dev = true;
    }

    Manual.convert(step, options);
  });

Program.parse(process.argv);
